services:
    frontend:
        image: akopij70/hotelup.frontendfix:latest
        environment:
            COGNITO_AUTHORITY: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_m6K9nuUJX"
            COGNITO_CLIENT: "647shjif56vvil39tsiklne5jd"
            REDIRECT_URI: "http://localhost:5173"
            COGNITO_DOMAIN: "https://hotelup.auth.us-east-1.amazoncognito.com"
            LOGOUT_URI: "http://localhost:5173"
            BACKEND_URL: "http://localhost:5000"
        ports:
            - "5173:5173"
    customer:
        image: wiaz/hotelup.customer:latest
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        ports:
            - "5000:8080"
        volumes:
            - $HOME/.aws/credentials:/home/app/.aws/credentials
        networks:
            - hotelup
        depends_on:
            - postgres
            - rabbitmq

    cleaning:
        image: wiaz/hotelup.cleaning:latest
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        ports:
            - "5004:8080"
        volumes:
            -  $HOME/.aws/credentials:/home/app/.aws/credentials
        networks:
            - hotelup
        depends_on:
            - postgres
            - rabbitmq
    
    information:
        image: wiaz/hotelup.information:latest
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        ports:
            - "5003:8080"
        volumes:
            - $HOME/.aws/credentials:/home/app/.aws/credentials
        networks:
            - hotelup
        depends_on:
            - postgres
            - rabbitmq

    kitchen:
        image: wiaz/hotelup.kitchen:latest
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        ports:
            - "5006:8080"
        volumes:
            - $HOME/.aws/credentials:/home/app/.aws/credentials
        networks:
            - hotelup
        depends_on:
            - postgres
            - rabbitmq

    employee:
        image: wiaz/hotelup.employee:latest
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        ports:
            - "5002:8080"
        volumes:
            - $HOME/.aws/credentials:/home/app/.aws/credentials
        networks:
            - hotelup
        depends_on:
            - postgres
            - rabbitmq
    
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
        ports:
            - "5432:5432"
        command:
            - "-c"
            - "config_file=/etc/postgresql.conf"
        volumes:
            - ./postgresql.conf:/etc/postgresql.conf
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - hotelup
    
    rabbitmq:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - hotelup
    
    seq:
        image: datalust/seq
        environment:
            ACCEPT_EULA: Y
        ports:
            - "5341:5341"
            - "80:80"
        networks:
            - hotelup

networks:
    hotelup:
        driver: bridge