services:
    customer:
        image: wiaz/hotelup.customer:latest
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        ports:
          - "5000:8080"
        volumes:
          - ${HOME}/.aws/credentials:/home/app/.aws/credentials
        networks:
            - hotelup
        depends_on:
            - postgres
            - rabbitmq

    cleaning:
        image: wiaz/hotelup.cleaning:latest
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        ports:
          - "5004:8080"
        volumes:
          - ${HOME}/.aws/credentials:/home/app/.aws/credentials
        networks:
            - hotelup
        depends_on:
            - postgres
            - rabbitmq
          
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
        ports:
        - "5432:5432"
        volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
        - hotelup
            
    rabbitmq:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
          - hotelup
        
    seq:
        image: datalust/seq
        environment:
            ACCEPT_EULA: Y
        ports:
            - "5341:5341"
            - "80:80"
        networks:
          - hotelup
    
networks:
    hotelup:
        driver: bridge