apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit-config
    namespace: kube-system
data:
    fluent-bit.conf: |
        [SERVICE]
            Flush         5
            Log_Level     info
            Daemon        off
            Parsers_File  parsers.conf

        [INPUT]
            Name              tail
            Path              /var/log/containers/*.log
            Parser            cri  # Dla EKS (zazwyczaj containerd)
            Tag               kube.*
            Refresh_Interval  5

        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc:443
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Merge_Log           On

        [OUTPUT]
            Name                cloudwatch
            Match               *
            region              <AWS_REGION>  # np. eu-central-1
            log_group_name      /aws/eks/<CLUSTER_NAME>/logs
            log_stream_prefix   fluent-bit-
            auto_create_group   true

    parsers.conf: |
        [PARSER]
            Name   cri
            Format regex
            Regex  ^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>P|F) (?<log>.*)$
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%LZ
