apiVersion: apps/v1
kind: Deployment
metadata:
    name: pgadmin-deployment
    namespace: hotelup
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pgadmin
    template:
        metadata:
            labels:
                app: pgadmin
        spec:
            containers:
              - name: pgadmin
                image: elestio/pgadmin:latest
                ports:
                  - containerPort: 80
                env:
                  - name: PGADMIN_DEFAULT_EMAIL
                    valueFrom:
                        secretKeyRef:
                            name: pgadmin-secret
                            key: email
                  - name: PGADMIN_DEFAULT_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: pgadmin-secret
                            key: password
---
apiVersion: v1
kind: Service
metadata:
    name: pgadmin-service
    namespace: hotelup
spec:
    selector:
        app: pgadmin
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 80
