apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: postgres-statefulset
    namespace: hotelup
    labels:
        app: postgres
spec:
    serviceName: postgres-service
    selector:
        matchLabels:
            app: postgres
    replicas: 1
    template:
        metadata:
            labels:
                app: postgres
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                            matchExpressions:
                              - key: app
                                operator: In
                                values: [ "postgres" ]
                        topologyKey: "kubernetes.io/hostname" # Spread pods across nodes
            containers:
              - name: postgres
                image: postgres:latest
                imagePullPolicy: IfNotPresent
                ports:
                  - containerPort: 5432
                env:
                  - name: PGDATA
                    value: /var/lib/postgresql/data/db-files
                  - name: POSTGRES_USER
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: user
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: password
                  - name: POSTGRES_DB
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: database
                volumeMounts:
                  - name: postgres-storage
                    mountPath: /var/lib/postgresql/data
                  - name: postgresql-conf-config
                    mountPath: /etc/postgresql.conf
                    subPath: postgresql.conf
                  - name: init-sql-config
                    mountPath: /docker-entrypoint-initdb.d/init.sql
                    subPath: init.sql
            volumes:
              - name: postgresql-conf-config
                configMap:
                    name: postgresql-conf-config
                    items:
                      - key: postgresql.conf
                        path: postgresql.conf
              - name: init-sql-config
                configMap:
                    name: init-sql-config
                    items:
                      - key: init.sql
                        path: init.sql
    volumeClaimTemplates:
      - metadata:
            name: postgres-storage
        spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "ebs-sc" # Use your StorageClass (e.g., "gp2", "aws-ebs")
            resources:
                requests:
                    storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: hotelup
spec:
    clusterIP: None
    selector:
        app: postgres
    ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
