apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-configmap
    namespace: hotelup
data:
    postgres-db: "testdb"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: postgres-statefulset
    namespace: hotelup
    labels:
        app: postgres
spec:
    serviceName: postgres-service
    selector:
        matchLabels:
            app: postgres
    replicas: 2
    template:
        metadata:
            labels:
                app: postgres
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                            matchExpressions:
                              - key: app
                                operator: In
                                values: [ "postgres" ]
                        topologyKey: "kubernetes.io/hostname" # Spread pods across nodes
            containers:
              - name: postgres
                image: postgres:latest
                imagePullPolicy: IfNotPresent
                ports:
                  - containerPort: 5432
                env:
                  - name: POSTGRES_USER
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: postgres-user
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: postgres-password
                  - name: POSTGRES_DB
                    valueFrom:
                        configMapKeyRef:
                            name: postgres-configmap
                            key: postgres-db
                volumeMounts:
                  - name: postgres-storage
                    mountPath: /var/lib/postgresql/data
            # volumes:
            #   - name: postgres-storage
            #     persistentVolumeClaim:
            #         claimName: postgres-pvc
    volumeClaimTemplates:
      - metadata:
            name: postgres-storage
        spec:
            accessModes: [ "ReadWriteOnce" ]
            # storageClassName: "gp2"  # Use your StorageClass (e.g., "gp2", "aws-ebs")
            resources:
                requests:
                    storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: hotelup
spec:
    clusterIP: None
    selector:
        app: postgres
    ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
